sudo: false # use container-based-infrastructure

env:
  global:
    - MAKEFLAGS="-j 2"

language: php

php: [7.0, 7.1]

install:
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - mkdir -p build/logs
  - make lint
  - make test
  - make examples

after_success:
  - travis_retry php bin/coveralls -v

cache:
    directories:
        - $HOME/.composer/cache
