sudo: false # use container-based-infrastructure

language: php

php: [5.5, 5.6, 7.0]

install:
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - php bin/phpcs --standard=PSR2 ./src/ --report=full
  - php bin/phpspec run --format=pretty -v

cache:
    directories:
        - $HOME/.composer/cache

